VotingBackend/Models/Voting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VotingBackend.Models
{
    public class Voting
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public int VotersCount { get; set; }
        public DateTime DueDate { get; set; }
        public Guid CategoryId { get; set; }

        public Category Category { get; set; }
        public virtual ICollection<User> Voters { get; set; }

    }
}

VotingBackend/Controllers/VotingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sieve.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using VotingBackend.Constants;
using VotingBackend.Dtos;
using VotingBackend.Exceptions;
using VotingBackend.Models;
using VotingBackend.Services;

namespace VotingBackend.Controllers
{
    [Produces("application/json")]
    [Route("api/voting")]
    [ApiController]
    public class VotingController : ControllerBase
    {
        private readonly IVotingService _service;

        public VotingController(IVotingService service)
        {
            _service = service;
        }

        [HttpGet]
        [Authorize(Roles = Constant.ROLE_ADMIN + "," + Constant.ROLE_CLIENT)]
        public async Task<ActionResult<Voting>> Index([FromQuery] SieveModel sieveModel)
        {
            return Ok(await _service.GetAllVoting(sieveModel)); 
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<VotingDto>> Index(Guid id)
        {
            try
            {
                var votingDetail = await _service.GetVoteDetail(id);
                return Ok(votingDetail);
            } 
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        [HttpPost]
        [Authorize(Roles = Constant.ROLE_ADMIN)]
        public async Task<ActionResult<CreateVotingResponseDto>> Create(CreateVotingRequestDto request)
        {
            var voting = await _service.CreateVoting(request);
            return Ok(voting);
        }

        [HttpPost("vote")]
        [Authorize(Roles = Constant.ROLE_CLIENT)]
        public async Task<ActionResult<VotingDto>> Vote(VoteRequestDto request)
        {
            try
            {
                var userId = new Guid(User.Identities.First().Name);
                var voting = await _service.Vote(request, userId);
                return Ok(voting);
            }
            catch (Exception ex)
            {
                if(ex is HttpExceptionBase)
                {
                    return BadRequest(ex);
                }
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        
    }
}

VotingBackend/Controllers/VotingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VotingBackend.Data;
using VotingBackend.Models;
using System.Linq;
using VotingBackend.Services.Web;
using VotingBackend.ViewModel;
using System.Net.Http;

namespace VotingBackend.Controllers
{

    [Route("votings")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class VotingsController : Controller
    {
        private readonly ICategoriesService _categoriesService;
        private readonly IVotingsService _votingsService;

        public VotingsController(ICategoriesService categoriesService, IVotingsService votingsService)
        {
            _categoriesService = categoriesService;
            _votingsService = votingsService;
        }

        // GET: Votings

        [Route("")]
        [Route("{page:int}")]
        public async Task<IActionResult> Index([FromRoute] int page, string searchString, Guid selectedCategory)
        {
            if (page > 0) page -= 1;
            if (Request.Method == HttpMethod.Post.Method)
            {
                page = 0;
            }

            var (votings, pageNum) = await _votingsService.Filter(searchString, selectedCategory, page);

            var categories = await _categoriesService.GetAll();
            categories.Insert(0, new CategoryViewModel { ID = Guid.Empty,Name = "--All--" });
            ViewData["Categories"] = new SelectList(categories, "ID", "Name");
            ViewData["PageNum"] = pageNum;
            return View(votings);
        }

        [Route("Details")]
        // GET: Votings/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voting = await _votingsService.Details((Guid) id);
            if (voting == null)
            {
                return NotFound();
            }

            return View(voting);
        }

        [Route("Create")]
        // GET: Votings/Create
        public async Task<IActionResult> Create()
        {
            var categories = await _categoriesService.GetAll();
            ViewData["CategoryId"] = new SelectList(categories, "ID", "Name");
            return View();
        }

        // POST: Votings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,DueDate,CategoryId")] VotingViewModel voting)
        {
            if (ModelState.IsValid)
            {
                await _votingsService.Create(voting);
                return RedirectToAction(nameof(Index));
            }
            
             var categories = await _categoriesService.GetAll();
            ViewData["CategoryId"] = new SelectList(categories, "ID", "Name");
            return View(voting);
        }

        // GET: Votings/Edit/5
        [Route("Edit")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voting = await _votingsService.Details((Guid)id);
            if (voting == null)
            {
                return NotFound();
            }

            var categories = await _categoriesService.GetAll();
            ViewData["CategoryId"] = new SelectList(categories, "ID", "Name", voting.CategoryId);
            return View(voting);
        }

        // POST: Votings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,Name,Description,DueDate,CategoryId")] VotingViewModel voting)
        {
            if (id != voting.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _votingsService.Edit(voting);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VotingExists(voting.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var categories = await _categoriesService.GetAll();
            ViewData["CategoryId"] = new SelectList(categories, "ID", "Name", voting.CategoryId);
            return View(voting);
        }

        // GET: Votings/Delete/5
        [Route("Delete")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voting = await _votingsService.Details((Guid)id);
            if (voting == null)
            {
                return NotFound();
            }

            return View(voting);
        }

        // POST: Votings/Delete/5
        [Route("Delete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _votingsService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool VotingExists(Guid id)
        {
            return _votingsService.IsVotingExists(id);
        }
    }
}

VotingBackend/Views/Votings/Create.cshtml
@model VotingBackend.ViewModel.VotingViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, VotingBackend

@{
    ViewData["Title"] = "Create";
}

<h4>Voting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VotingBackend/Views/Votings/Delete.cshtml
@model VotingBackend.ViewModel.VotingViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, VotingBackend

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voting</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VotersCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VotersCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VotingBackend/Views/Votings/Details.cshtml
@model VotingBackend.ViewModel.VotingViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, VotingBackend

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Voting</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VotersCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VotersCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VotingBackend/Views/Votings/Edit.cshtml
@model VotingBackend.ViewModel.VotingViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, VotingBackend

@{
    ViewData["Title"] = "Edit";
}

<h4>Voting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VotingBackend/Views/Votings/Index.cshtml
@model IEnumerable<VotingBackend.ViewModel.VotingViewModel>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, VotingBackend

@using System.Collections
@using VotingBackend.ViewModel

@{
    ViewData["Title"] = "Index";
}

<form asp-controller="Votings" asp-action="Index">
    <p>
        <div class="row my-2">
            <div class="col-md-3">Title</div>
            <div class="col-md-6"> <input type="text" name="SearchString" /></div>
        </div>
        <div class="row my-2">
            <div class="col-md-3">Category</div>
            <div class="col-md-6"><select name="selectedCategory" class="form-control" asp-items="ViewBag.Categories"></select></div>
        </div>
        <div class="r0w"><input type="submit" value="Filter" /></div>
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VotersCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VotersCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>



<nav aria-label="Page navigation example">
    <ul class="pagination">
        @for (var i = 1; i <= (int)ViewData["PageNum"]; i++)
        {
            <li class="page-item"><a class="page-link"asp-action="@i">@i</a></li>
        }
    </ul>
</nav>